apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cnpg-tps-scaler
spec:
  scaleTargetRef:
    apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    name: pg-autoscale
  minReplicaCount: 2
  maxReplicaCount: 5
  pollingInterval: 5
  cooldownPeriod: 60
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.monitoring.svc:9090
        metricName: postgres_tps_rate
        threshold: "500"
        query: |
          sum(irate(cnpg_pg_stat_database_xact_commit{cluster_name="pg-autoscale", datname="postgres"}[1m]))