apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-controller
rules:
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["clusters"]
    verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storage-controller
subjects:
  - kind: ServiceAccount
    name: storage-controller
    namespace: default
roleRef:
  kind: ClusterRole
  name: storage-controller
  apiGroup: rbac.authorization.k8s.io
