apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  instances: 1
  storage:
    size: 5Gi
  serviceAccountTemplate:
    metadata:
      annotations:
        iam.gke.io/gcp-service-account: cnpg-backup-sa@project-eea01d7e-b0e2-44f2-976.iam.gserviceaccount.com
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - gke-auto-scaling-lab-default-pool-ba812d2f-pflx
  backup:
    volumeSnapshot:
      className: cnpg-snapshot-class     
    target: prefer-standby
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: pg-objectstore
  monitoring:
    customQueriesConfigMap:
      - name: cnpg-custom-queries
        key: queries
    metricsQueriesTTL: 15s
    disableDefaultQueries: true
  bootstrap: 
    initdb:
      database: app
      owner: app
      secret:
        name: pg-cluster-app-user
  postgresql:                                                               
    parameters:                                                    
      max_connections: "120"
      shared_buffers: "1024MB"
      wal_buffers: "64MB"
      max_wal_size: "6GB"
      min_wal_size: "2GB"
      checkpoint_completion_target: "0.9"
      checkpoint_timeout: "15min"
      synchronous_commit: "off"
      wal_compression: "on"
      default_statistics_target: "100"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
