apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-custom-queries
  namespace: default

data:
  queries: |
    pg_tps:
      query: |
        SELECT
          datname,
          xact_commit,
          xact_rollback
        FROM pg_stat_database
        WHERE datname = current_database()

      metrics:
        - datname:
            usage: "LABEL"
            description: "Database name"

        - xact_commit:
            usage: "COUNTER"
            description: "Committed transactions"

        - xact_rollback:
            usage: "COUNTER"
            description: "Rolled back transactions"

    pg_active_backends:
      query: |
        SELECT
          usename,
          state,
          count(*) AS backends_total
        FROM pg_stat_activity
        WHERE state = 'active'
        GROUP BY usename, state

      metrics:
        - usename:
            usage: "LABEL"
            description: "Database user"

        - state:
            usage: "LABEL"
            description: "Backend state"

        - backends_total:
            usage: "GAUGE"
            description: "Number of backends"

    pg_statements_aggregate:
      query: |
        SELECT
          sum(calls) AS calls,
          sum(total_exec_time) / 1000 AS total_exec_time_seconds
        FROM pg_stat_statements

      metrics:
        - calls:
            usage: "COUNTER"
            description: "Total statement calls"

        - total_exec_time_seconds:
            usage: "COUNTER"
            description: "Total execution time in seconds"