apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: pg-objectstore
spec:
  configuration:
    destinationPath: gs://cnpg-wal-archive-project-eea01d7e-b0e2-44f2-976/pg-cluster
    googleCredentials:
      gkeEnvironment: true
    wal:
      compression: gzip
      maxParallel: 4
