apiVersion: v1
kind: Service
metadata:
  name: pg-cluster-headless
  namespace: default
spec:
  clusterIP: None
  selector:
    cnpg.io/cluster: pg-cluster
    cnpg.io/podRole: instance
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
