{
 "title": "Storage Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Disk Usage Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max((1 - kubelet_volume_stats_available_bytes{namespace=\"default\", persistentvolumeclaim=~\"pg-cluster-[0-9]+\"}/ kubelet_volume_stats_capacity_bytes{namespace=\"default\", persistentvolumeclaim=~\"pg-cluster-[0-9]+\"})* 100)",
     "legendFormat": "Disk Usage Ratio"
    }
   ]
  },
  {
   "title": "Disk Fill Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "clamp_min(-deriv(kubelet_volume_stats_available_bytes{namespace=\"default\",persistentvolumeclaim=~\"pg-cluster-[0-9]+\"}[4m]) / 1024 / 1024, 0)",
     "legendFormat": "Disk Fill Rate"
    }
   ]
  },
  {
   "title": "Growth Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "quantile_over_time(\n    0.95,\n    (\n      -deriv(\n        kubelet_volume_stats_available_bytes{\n          namespace=\"default\",\n          persistentvolumeclaim=~\"pg-cluster-[0-9]+\"\n        }[5m]\n      )\n    )[20m:30s]) / 1024 / 1024",
     "legendFormat": "Long-term rate"
    },
    {
     "expr": "quantile_over_time(\n    0.99,\n    (\n      -deriv(\n        kubelet_volume_stats_available_bytes{\n          namespace=\"default\",\n          persistentvolumeclaim=~\"pg-cluster-[0-9]+\"\n        }[3m]\n      )\n    )[10m:15s]\n  ) / 1024 / 1024 ",
     "legendFormat": "Short-tem rate"
    }
   ]
  },
  {
   "title": "PVC Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"default\", persistentvolumeclaim=~\"pg-cluster-[0-9]+\"}) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage % (Current)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((1 - kubelet_volume_stats_available_bytes{namespace=\"default\", persistentvolumeclaim=~\"pg-cluster-[0-9]+\"}/ kubelet_volume_stats_capacity_bytes{namespace=\"default\", persistentvolumeclaim=~\"pg-cluster-[0-9]+\"}) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS (Write Throughput)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cnpg_pg_stat_database_xact_commit{namespace=\"default\", pod=~\"pg-cluster-.*\"}[2m]))+ sum(rate(cnpg_pg_stat_database_xact_rollback{namespace=\"default\", pod=~\"pg-cluster-.*\"}[2m]))",
     "legendFormat": "TPS"
    }
   ]
  }
 ]
}