apiVersion: v1
kind: Service
metadata:
  name: auto-run
  namespace: default
  labels:
    app: auto-run
spec:
  selector:
    app: auto-run
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
