apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  instances: 4

  imageName: ghcr.io/cloudnative-pg/postgresql:16.1

  primaryUpdateStrategy: unsupervised

  storage:
    size: 10Gi

  superuserSecret:
    name: pg-secret

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      wal_level: replica
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
  
  monitoring:
    customQueriesConfigMap:
      - name: pg-custom-metrics
        key: queries